name: linux

on:
  push:
    tags:
      - "*"

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v1
      - name: setup
        run: |
          sudo apt update
          cd ../..
          git clone https://github.com/open-ephys/plugin-GUI.git --branch main
          sudo ./plugin-GUI/Resources/Scripts/install_linux_dependencies.sh
          cd plugin-GUI/Build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
      - name: build
        run: |
          cd Build
          cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
          make
      - name: package
        env:
          plugin-name: UDPEvents-linux
          tag: "${{ github.ref_name }}"
        run: |
          plugin_api=$(grep -rnw ../../plugin-GUI/Source -e '#define PLUGIN_API_VER' | grep -Eo "[0-9]*" | tail -1)
          new_plugin_ver=$tag-API$plugin_api
          mkdir plugins 
          cp -r Build/*.so plugins
          zipfile=${plugin-name}_${new_plugin_ver}.zip
          zip -r -X $zipfile plugins
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: UDPEvents-linux
          path: "*.zip"
