name: windows

on:
  push:
    tags:
      - "*"
env:
  plugin_name: "UDPEvents-windows"
  tag: "${{ github.ref_name }}"

jobs:
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]

    steps:
      - uses: actions/checkout@v1
      - name: setup
        shell: bash
        run: |
          cd ../..
          git clone https://github.com/open-ephys/plugin-GUI.git --branch main
          cd plugin-GUI/Build
          cmake -G "Visual Studio 17 2022" -A x64 ..
          mkdir Release && cd Release
          curl -L https://openephys.jfrog.io/artifactory/GUI-binaries/Libraries/open-ephys-lib-v0.6.0.zip --output open-ephys-lib.zip
          unzip open-ephys-lib.zip
      - name: configure
        shell: bash
        run: |
          cd Build
          cmake -G "Visual Studio 17 2022" -A x64 ..
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: build-plugin
        shell: cmd
        run: |
          cd Build
          msbuild INSTALL.vcxproj -p:Configuration=Release -p:Platform=x64
      - name: versioning
        shell: bash
        run: |
          plugin_api=$(grep -rnw ../../plugin-GUI/Source -e '#define PLUGIN_API_VER' | grep -Eo "[0-9]*" | tail -1)
          new_plugin_ver=$tag-API$plugin_api
          echo "artifact_name=${plugin_name}_${new_plugin_ver}" >> "$GITHUB_ENV"
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.artifact_name }}"
          path: "Build/Release/*.dll"
